name: stronz_video_player
description: "stronz_video_player"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  flutter_hls_parser: ^2.0.1
  http: ^1.2.2
  provider: ^6.1.2
  video_player: ^2.9.1
  path_provider: ^2.1.4
  window_manager: ^0.4.2
  mime: ^1.0.5
  audio_service: ^0.18.15
  image: ^4.2.0
  smtc_windows:
    git:
      url: https://github.com/Bonfra04/smtc_windows.git
      path: ./packages/smtc_windows
      ref: main

  video_player_media_kit: ^1.0.5
  media_kit_libs_android_video: any
  media_kit_libs_ios_video: any
  media_kit_libs_macos_video: any
  media_kit_libs_windows_video: any
  media_kit_libs_linux: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
