name: stronz_video_player
description: "stronz_video_player"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  flutter_hls_parser: ^2.0.1
  http: ^1.2.2
  provider: ^6.1.2
  video_player: ^2.9.1
  fvp: ^0.24.1
  path_provider: ^2.1.4
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
