name: stronz_video_player
description: "stronz_video_player"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sutils:
    git: https://github.com/StronzLabs/SUtils.git

  async: ^2.11.0
  provider: ^6.1.2

  flutter_hls_parser:
    git: https://github.com/Bonfra04/flutter_hls_parser.git
  path_provider: ^2.1.4

  wakelock_plus: ^1.2.8
  image: ^4.2.0
  audio_service: ^0.18.15
  audio_service_mpris: ^0.1.5
  smtc_windows:
    git:
      url: https://github.com/Bonfra04/smtc_windows.git
      path: ./packages/smtc_windows
      ref: main

  video_player: ^2.9.2
  video_player_win:
    git:
      url: https://github.com/jakky1/video_player_win.git
      ref: support_http_headers
  fvp:
    git: https://github.com/wang-bin/fvp.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  video_player:
    git:
      url: https://github.com/flutter/packages.git
      path: ./packages/video_player/video_player
